## File with controls to add dinamically to app
{
  controls: [
    ZoomIn,
    ZoomOut,
    ZoomBox,
    Scale,
    ScaleLine,
    MousePosition,
    Navigation,
    NavigationHistory,
    ZoomToMaxExtent,
    PermalinkButton,
    HelpButton,
    MeasureLine,
    MeasureArea,
    DrawFeature,
    CustomLayerSwitcher
  ]
}