# Layers parameters to map
##########################

## Layer service
## gets layers from URL with urlServiceLayer, it if '' or null 
## control loads default layers
urlServiceLayer : null
layers :
## Topografico layer
- map_name : default
  layer_name : Topográfico-IDEE
  wms_layer : mtn_rasterizado
  wms_url : http://www.idee.es/wms/MTN-Raster/MTN-Raster
  visible: true
  layer_position : 2
  parameters : {opacity : 0.75, singleTile : false, projection : 'EPSG:23029'}
  is_base : true
## IGN Layer
- map_name : default
  layer_name : IGN Base
  wms_layer : IGNBaseTodo
  wms_url : http://www.ign.es/wms-inspire/ign-base
  visible : true
  layer_position : 1
  parameters : {opacity : 0.75, singleTile : false, projection : 'EPSG:23029'}
  is_base : true
