# Layers parameters to map
##########################
{
  ## Layer service
  ## gets layers from URL with urlServiceLayer, it if '' or null 
  ## control loads default layers
  urlServiceLayer : !!null null,
  layers : [ {
  ## Topografico layer
    map_name : default,
    type : 'wms',
    layer_name : Topográfico-IDEE,
    wms_layer : mtn_rasterizado,
    url : 'http://www.idee.es/wms/MTN-Raster/MTN-Raster',
    parameters : {
      opacity : !!float 0.75,
      group_name : '',
      layer_position : !!int 1,
      singleTile : !!bool false,
      isBaseLayer : !!bool true,
      visibility: !!bool true,
      projection : 'EPSG:23029'
    }
  }, {
  ## IGN Layer
    map_name : default,
    type : 'wms',
    layer_name : IGN Base,
    wms_layer : IGNBaseTodo,
    url : 'http://www.ign.es/wms-inspire/ign-base',
    parameters : {
      opacity : !!float 0.75,
      group_name : '',
      layer_position : !!int 2,
      singleTile : !!bool false,
      isBaseLayer : !!bool true,
      visibility: !!bool true,
      projection : 'EPSG:23029'
    }
  }, {
  ## GeoJson Layer
    map_name : default,
    layer_name : GJson,
    type : 'geojson',
    url : 'config/layer.json',
    parameters: {
      group_name : 'prueba/json',
      visibility : !!bool true,
      layer_position : !!int 2,
      projection : 'EPSG:23029',
      isBaseLayer : !!bool false
    }
  }
  #, {
  ## GeoJson AJAX Layer
  #  map_name : default,
  #  layer_name : GJson,
  #  type : 'ajax',
  #  url : 'http://127.0.0.1:8000/api/upai/?format=jsonp',
  #  parameters: {
  #    group_name : 'prueba/json/',
  #    visibility : !!bool true,
  #    layer_position : !!int 2,
  #    projection : 'EPSG:23029',
  #    isBaseLayer : !!bool false
  #  }
  #}
  ]
}