# Layers parameters to map
##########################
{
  ## Layer service
  ## gets layers from URL with urlServiceLayer, it if '' or null 
  ## control loads default layers
  urlServiceLayer : !!null null,
  layers : [ {
  ## Topografico layer
    map_name : default,
    group_name : capa_base,
    type : 'wms',
    layer_name : Topográfico-IDEE,
    wms_layer : mtn_rasterizado,
    url : 'http://www.idee.es/wms/MTN-Raster/MTN-Raster',
    visible: !!bool true,
    layer_position : !!int 1,
    parameters : {opacity : !!float 0.75, singleTile : !!bool false, projection : 'EPSG:23029'},
    is_base : !!bool true
  }, {
  ## IGN Layer
    map_name : default,
    group_name : capa_base,
    type : 'wms',
    layer_name : IGN Base,
    wms_layer : IGNBaseTodo,
    url : 'http://www.ign.es/wms-inspire/ign-base',
    visible : !!bool true,
    layer_position : !!int 2,
    parameters : {opacity : !!float 0.75, singleTile : !!bool false, projection : 'EPSG:23029'},
    is_base : !!bool true
  }, {
  ## GeoJson Layer
    map_name : default,
    layer_name : GJson,
    type : 'geojson',
    url : 'config/layer.json',
    parameters: {
      group_name : prueba,
      visibility : !!bool true,
      layer_position : !!int 2,
      projection : 'EPSG:23029',
      isBaseLayer : !!bool false
    }
  } ]
}