## File with controls to add dinamically to app
{
  controls: [
    Scale,
    ScaleLine,
    MousePosition,
    Navigation,
    NavigationHistory,
    ZoomIn,
    ZoomOut,
    ZoomBox,
    ZoomToMaxExtent,
    PermalinkButton,
    HelpButton,
    MeasureLine,
    MeasureArea
  ]
}